<?php

namespace App\Repositories;

use App\Cinema;
use App\Repositories\Abstracts\CRUDModelAbstract;
use App\Repositories\Interfaces\CinemaRepositoryInterface;

/**
 * Class CinemaRepository
 *
 * @package App\Repositories
 */
class CinemaRepository extends CRUDModelAbstract implements CinemaRepositoryInterface
{
    use LoggerTrait;

    protected $model = Cinema::class;

    /**
     * Create new cinema
     *
     * @param array $fields
     * @param bool $isWriteLog
     * @return mixed
     * @throws \Exception
     */
    public function create($fields = [], bool $isWriteLog = true)
    {
        try {
            return parent::create($fields); // TODO: Change the autogenerated stub
        } catch (\Exception $e) {
            throw new \Exception($e->getMessage());
        }
    }

    /**
     * Update Cinema
     *
     * @param null $modelId
     * @param null $model
     * @param array $fields
     * @param bool $isWriteLog
     * @return Cinema|\Illuminate\Database\Eloquent\Model
     * @throws \Exception
     */
    public function update($modelId = null, $model = null, $fields = [], bool $isWriteLog = true)
    {
        try {
            /** @var Cinema $cinema */
            $cinema = parent::update($modelId, $model, $fields); // TODO: Change the autogenerated stub
            if ($cinema) {
                $this->updateLog($cinema, Cinema::class);
                return $cinema;
            }
        } catch (\Exception $e) {
            throw new \Exception($e->getMessage());
        }
    }

    /**
     * Destroy cinema
     *
     * @param null $modelId
     * @param null $model
     * @param bool $isWriteLog
     * @return bool|\Illuminate\Database\Eloquent\Model
     * @throws \Exception
     */
    public function delete($modelId = null, $model = null, bool $isWriteLog = true)
    {
        try {
            $cinema = parent::delete($modelId, $model); // TODO: Change the autogenerated stub
            if ($cinema) {
//                $cinema->shows()->delete();
                $this->deleteLog($cinema, Cinema::class);
            }
            return $cinema;
        } catch (\Exception $e) {
            throw new \Exception($e->getMessage());
        }
    }
}
